### ISSUE TITLE
Sanitize the branch name in Helm release names

### ISSUE THREAD

**Issue by galdorjt** [jobteaser/circleci#1]
In the `helm` orb, the default value of the Helm release name is `$CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH`. This is a problem because the name of the branch may contain characters which are not authorized in Helm release names.

The name should be transformed to only contain authorized characters.

**Comment by gearnode** [comment]
We can close this issue or you work on it?

**Comment by cansjt** [comment]
Would be nice to work on this. Dependabot PR, for example, cannot be deployed. Feature or bug, I don't know ?

One occurrence: https://circleci.com/gh/jobteaser/data-tracking-plan/2223?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by gearnode** [comment]
@galdorjt ping

**Comment by galdorjt** [comment]
Sorry, it is not going to happen. Just use valid Helm release characters.
