### ISSUE TITLE
Helm lint command should be given the same variables as the upgrade or install one

### ISSUE THREAD

**Issue by cansjt** [jobteaser/circleci#22]
## Issue

If `helm`'s linting command is not given all the variables used by the deployment, it will fail if the `_helpers.tpl` makes use of any of these variable. Which it may.

Example, with all the variables:
```
$ helm lint ./k8s/jobflow/ \
    --set=circleci.sha1=e1011e0757985241122f87ac6b61c4cee5cf0e0a \
    --set=image=jobteaser/jobdata:git-stats-e1011e0757985241122f87ac6b61c4cee5cf0e0a 
==> Linting ./k8s/jobflow/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```
With some missing variables:
```
$ helm lint ./k8s/jobflow/ \
    --set=image=jobteaser/jobdata:git-stats-e1011e0757985241122f87ac6b61c4cee5cf0e0a 
==> Linting ./k8s/jobflow/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "jobflow/templates/deployment.yaml": template: jobflow/templates/deployment.yaml:24:70: executing "jobflow/templates/deployment.yaml" at <.Values.circleci.sha1>: nil pointer evaluating interface {}.sha1

Error: 1 chart(s) linted, 1 chart(s) failed
```

## Work-around

For now one can disable linting.

## Fix

Would gladly offer a PR, though I am not sure yet how one could "macro" this to not have to repeat those arguments in several places in the orb. The stupid fix is easy enough though, if the smarter one is not possible.

**Comment by gearnode** [comment]
@cansjt You have to add default image variable on your helm chart. For example: `jobteaser/example-service:latest`.

BTW, keep your patch for `-set=circleci.branch`
