### ISSUE TITLE
Have deployment push notifications to monitoring systems

### ISSUE THREAD

**Issue by cansjt** [jobteaser/circleci#26]
Monitoring sytems like Grafana, DataDog, etc. often have the ability to push specialized "events" to log events that impact an infrastructure on global level.

The goal is to help correlate such events with changes in behavioral patterns of the monitored system(s): e.g. by overlaying those events on all the timeseries displayed on a dashboard.

Talking with @maajt, he told me such events used to be published to Kafka and then dispatched to the relevant stores (to what topic ?). The point of using Kafka is to simplify event publication, but requires an additional component for the dispatch.

## References

DataDog's [events](https://docs.datadoghq.com/api/?lang=bash#events)
Grafana's [annotations](https://grafana.com/docs/http_api/annotations/).

**Comment by galdorjt** [comment]
It is significantly simpler to make HTTP calls, but I agree that having a dedicated Kafka topic for this usage would be so much better. Of course it means a service has to listen to it and them make the HTTP calls.

I agree it is useful, and yes we can try to schedule it.

**Comment by gearnode** [comment]
I have some script for do this, but after exchange with the infra team our grafana setup has no backup... So we can lose all annonation we send.

**Comment by galdorjt** [comment]
Let's keep the idea, and see if we can build something in 2020 Q1.

**Comment by gearnode** [comment]
Done, each deploy push notification on signalfx.
