### ISSUE TITLE
[helm] Unused parameter `kubernetes_deployment` declared

### ISSUE THREAD

**Issue by cansjt** [jobteaser/circleci#28]
In the helm orb, the deploy task declares a [`kubernetes_deployment`](https://github.com/jobteaser/circleci/blob/master/orbs/helm/orb.yml#L176) parameter it does not use. So I guess it should be removed.

**Comment by cansjt** [comment]
See enclosed patch.

[remove-kubernetes-deployment-parameter.patch.txt](https://github.com/jobteaser/circleci/files/3919158/remove-kubernetes-deployment-parameter.patch.txt)

**Comment by gearnode** [comment]
@cansjt You right it's legacy keep  used to monitor the status of Kubernetes deployment. We use helm to do this now. 

Thanks for the patch I apply this morning.
