### ISSUE TITLE
[docker] Pass CIRCLE_SHA1 and CIRCLE_BRANCH as arguments to `docker build`

### ISSUE THREAD

**Issue by cansjt** [jobteaser/circleci#29]
In relation to this question on the [service spec](https://github.com/jobteaser/service/issues/5), shouldn't we add the following build args to the build_image command in the docker orb ?
```
docker build ... \
    --build-arg "GIT_HASH=$CIRCLE_SHA1" \
    --build-arg "GIT_BRANCH=$CIRCLE_BRANCH" \
    ...
```
I checked, if the docker file does not declare "ARG GIT_HASH" _etc._ that does not break the build so it seems fairly safe (w. `Docker version 19.03.5`).

[build-args.patch.txt](https://github.com/jobteaser/circleci/files/3949286/build-args.patch.txt)

**Comment by cansjt** [comment]
Implementation example: https://github.com/jobteaser/tracking/pull/95

**Comment by galdorjt** [comment]
As explained in #5, you do not need any of this, you can just call the `service/generate_build_info` command in your CircleCI job. Since the file is generated in the `data` directory, there is nothing more to do since this directory is entirely copied into the Docker image.
