### ISSUE TITLE
Support the `version` key for setup_remote_docker (orb's docker/setup command)

### ISSUE THREAD

**Issue by cansjt** [jobteaser/circleci#34]
Un patch vaut mieux qu'un long discours (toujours pas possible de pousser sur cet entrepôt).

[~0001-Add-docker-daemon-version-selection.patch.txt~](https://github.com/jobteaser/circleci/files/4184731/0001-Add-docker-daemon-version-selection.patch.txt)

**Comment by cansjt** [comment]
Updated version of the patch. Adds the same parameter at the job level as at the command level.

[0001-Add-docker-daemon-version-selection.patch.txt](https://github.com/jobteaser/circleci/files/4239065/0001-Add-docker-daemon-version-selection.patch.txt)

**Comment by galdorjt** [comment]
@gearnode beyond the typo, I do not see anything wrong; what do you think about it ?

**Comment by cansjt** [comment]
Typo fixed. Hopefully no other hanging around. Updated patch below.
[0001-Add-docker-daemon-version-selection.patch.txt](https://github.com/jobteaser/circleci/files/4245194/0001-Add-docker-daemon-version-selection.patch.txt)

**Comment by gearnode** [comment]
I am not sure about have configurable docker version. Can we just bump the current version we use? To keep the same builder everywhere.

**Comment by gearnode** [comment]
So we can update the version but we should allow version as parameters. Can you tell us the docker version you would?

**Comment by cansjt** [comment]
I had picked the latest version available: "18.09.3" for [the documentation](https://circleci.com/docs/2.0/building-docker-images/#docker-version)
