### ISSUE TITLE
Troubleshooting section about purging first failed deploy in bootstrap doc

### ISSUE THREAD

**Issue by ejoubaud** [jobteaser/circleci#42]
Follow-up to jobteaser/service#10

A common issue people always seem to run into when bootstrapping their service is the first deploy fails for some reason (often the pg db isn't up-and-running yet, or not well configured) and then subsequent deploys all fail with this error message: `Error: UPGRADE FAILED: "${service_name}-master" has no deployed releases`.

The fix is not that easy to figure out for k8s novices (as most of us are) but pretty trivial when you know it, you just need to purge the failed deployment:

- `kubectl logs <pod name>` will tell you what failed, fix it then:
- `helm --tiller-namespace <servicename> list -a` will let you see the failed deploy
- `helm delete --tiller-namespace <servicename> --purge <deployname>` will let you purge it

Since it's so common I think it would make sense to document that issue in the bootstrapping doc. Not sure if the best place for it is jobteaser/service or here. Maybe here since the error can be seen in CircleCI and the deployment/CircleCI steps are documented in this repo's bootstrap.md

**Comment by gearnode** [comment]
close ref to previous issue.

**Comment by ejoubaud** [comment]
Opened jobteaser/service#11. FWIW I still think the bootstrap doc here could use a link to it though: people are way more likely to find it if it's in the doc they're following.
