### ISSUE TITLE
[helm] The tag_deployment job is not self contained !

### ISSUE THREAD

**Issue by cansjt** [jobteaser/circleci#85]
We had, at some point, the `helm/tag_deployment` task running successfully. But for a long while now, this tasks systematically fails, which means all our deployments in production (on some repositories) fail, with this error:
```
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Exited with code exit status 128
```

It seem obvious thig is a git/github permission issue. It seems the tasks depends on the JobTomate user. But I don't see any reason why we would need a user with so many privileges just to tag commits. (Nor do I want to "invite" him on my repositories).

Could there be some documentation, in the task's description, some explanations with respect to what is need to make this work.
If there exist a user we can use that is not all powerful on the JT organisation, that would also be nice to mention.

**Comment by cphu-jt** [comment]
Hello, you can use circleci-jt user which have limited access.
Process is described here 
https://github.com/jobteaser/circleci/blob/master/doc/bootstrap.md#checkout-key

**Comment by cansjt** [comment]
@cphu-jt I read the documentation you provided. I thought I'd find an example, but nobody seem to have done what's described there.
For the moment I [opened this PR](https://github.com/jobteaser/github/pull/472).
And tried to add the user key for tome repositories. Managed to do if for 2, but for two others `circleci-jt` does not seem to be allowed to access their settings (`analytics-api` & `tracking`). What am I missing ?
